## Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

notifications:
    commits:       commits@jena.apache.org
    issues:        issues@jena.apache.org
    pullrequests:  pr@jena.apache.org

github:
  description: "Website sources for the Apache Jena website"
  homepage: https://jena.apache.org/
  labels:
    - apache
    - jena
    - hugo
    - website
  protected_branches:
    main
  features:
    issues: true
    discussions: false
  enabled_merge_buttons:
    squash: false
    rebase: true
    merge: false
