baseURL = "https://jena.apache.org"
title = "Apache Jena"
languageCode = "en"

contentDir = "source"
publishDir = "target/content"

disablePathToLower = true
uglyURLs = true
enableRobotsTXT = true
disableBrowserError = true
timeout = 3000

disableKinds = ["taxonomy", "taxonomyTerm"]
ignoreFiles = [ ] # No files to ignore

# Highlighting config. See https://help.farbox.com/pygments.html
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "emacs"

# Enable Git variables like commit, lastmod
enableGitInfo = true

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[markup.goldmark.renderer]
unsafe= true

[blackfriday]
# hrefTargetBlank = true # We don't want everything opened in a new window
fractions = false

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

[params]
repositoryUrl = "https://github.com/apache/jena"
repositorySourceBranch = "main"

siteRepositoryUrl = "https://github.com/apache/jena-site"
siteRepositorySourceBranch = "main"
